spring:
  application:
    name: school-bulletin
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/school_grade_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Pa$$Na$$aIW0rd}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

    locations: classpath:db/migration
  thymeleaf:
    cache: false

aws:
  eventBridge:
    bus: ${AWS_EVENT_BUS:default}
  s3:
    bucket: ${AWS_S3_BUCKET:school-bulletin-bucket}

app:
  jwt:
    secret: ${JWT_SECRET:defaultSecretKeyForSchoolBulletinProject2025MustBeAtLeast32Chars}
    expiration: ${JWT_EXPIRATION:86400000}
  admin:
    email: ${ADMIN_EMAIL:admin@hei.mg}
    password: ${ADMIN_PASSWORD:Admin123!}
    full-name: ${ADMIN_FULL_NAME:Administrateur}